### PR TITLE
Add Desiro HC RRX and not Mireo Plus H

### PR DESCRIPTION
**Pull request by C1710**
- Desiro HC RRX:
  - 4 part EMU, 105 m
  - vMax 160 km/h
  - 300kN
  - 200t
  - 400 Passengers
  - 1.2M Plops (real price: ~9M €, should be a bit lower than F./S.-TH)
  - compatible with Desiro HC Franken/Südthüringen (renamed), Mireo
(
- Mireo Plus H
  - 3 part HMU (here classified as DMU), 63 m
  - vMax 160 km/h
  - 112 kN (estimated)
  - 100 t (estimated from the "normal" Mireo)
  - 160 passengers
  - 700k Plops (real price unknown, should be more than 612, etc., since it's not even released)
  - 100 Plops/km (hydrogen should be more expensive)
  - Mostly pointless, since Diesel will probably be better, except for acceleration maybe
)

### CODE REVIEW

**Comment by ChillLP** [comment]
Use the Project for this Please 
https://github.com/users/marhei/projects/1
or do it yourself

**Comment by C1710** [comment]
> Use the Project for this Please https://github.com/users/marhei/projects/1 or do it yourself

I can't do anything in the project and I am adding the train(s) (right now it's only one) myself :D

**Comment by marhei** [comment]
Danke für deine Mühe, ich kümmere mich morgen drum.

**Review by marhei — CHANGES_REQUESTED** [review]
Bitte Twindexx Vario und Mireo Plus H entfernen. Beide sind derzeit technisch nicht umsetzbar.

**Comment by C1710** [comment]
> Bitte Twindexx Vario und Mireo Plus H entfernen. Beide sind derzeit technisch nicht umsetzbar.

☑

**Pull request merged**
